[package]
name = "ccfblack"
version = "0.1.0"
authors = ["komesu_tatsuki <komesu_tatsuki@trek.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"